workplace_admin:
    resource: "@WorkplaceAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

workplace_users:
    resource: "@WorkplaceUsersBundle/Resources/config/routing.yml"
    prefix:   /profile

workplace_api:
    resource: "@WorkplaceApiBundle/Resources/config/routing.yml"
    prefix:   /api

workplace_web:
    resource: "@WorkplaceWebBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
